### ISSUE TITLE
Support for Upsert

### ISSUE THREAD

**Issue by encima** [aiven/opensearch-connector-for-apache-kafka#116]
Following on from the [issue](https://github.com/aiven/elasticsearch-connector-for-apache-kafka/issues/50) in Aiven's ES connector, could we add support for this when using the bulk/document API?

**Comment by Prodyte** [comment]
any update on this?

**Comment by willyborankin** [comment]
@encima and @Prodyte thank you for your request this functionality will be added soon. Stay turned.

**Comment by willyborankin** [comment]
addressed here: https://github.com/aiven/opensearch-connector-for-apache-kafka/pull/160
