### ISSUE TITLE
A config that injects the Kafka event CREATETIME as an OpenSearch `date` on index creation

### ISSUE THREAD

**Issue by kandji-alex** [aiven/opensearch-connector-for-apache-kafka#122]
This has already been added to (and made customizable/optional) the [ElasticSearch Sink](https://github.com/confluentinc/kafka-connect-elasticsearch/pull/540). 

## Problem
This sink does not make it easy to inject the Kafka event CREATETIME into the event, and have the auto-generated index receive it properly as a `date` type. The only way I've found to do it with schema-less messages is to have it as a formatted string VERY specifically in ISO format.

For Protobuf, I still haven't figured out how to do it. The ISO format string doesn't create the field as a `date`.

## Solution
There should be a configuration that, when true, injects the Kafka event CREATETIME as the `@timestamp` field, of OpenSearch type `date`. It should work regardless of the message schea type (no schema, json, protobuf, avro).

There may be a good way to do this already, and if so, it should be added to the documentation.

**Comment by willyborankin** [comment]
This feature is about Data Streams. It was added recently and so far in main.

**Comment by willyborankin** [comment]
was added here https://github.com/aiven/opensearch-connector-for-apache-kafka/pull/158
