### ISSUE TITLE
add support for ingest pipeline api

### ISSUE THREAD

**Issue by franfreire** [aiven/opensearch-connector-for-apache-kafka#204]
We use the ingest pipeline api of opensearch for processing the logs before indexing in our opensearch. We've been using fluent-bit for send logs to opensearch and we could indicate the ingest pipeline that we want to use. 

https://docs.fluentbit.io/manual/pipeline/outputs/opensearch

But with opensearch connector for apache kafka the logs are being indexed directly and we haven't found any option to indicate any ingest pipeline.

We believe that it should not be difficult to implement, through a new "pipeline" option like in fluent-bit or elasticsearch filebeat

**Comment by willyborankin** [comment]
Hi @franfreire , you can use index settings:
```
 - `index.default_pipeline`
 - `index.final_pipeline`
```
to support ingest pipelines
